// Build-time generator: reads src/fixtures.ts and emits a real React
// component per fixture into src/components/generated/. The output imports
// shadcn primitives directly and inlines Tailwind classes — there is no
// @babel/parser or registry lookup at runtime.
//
// Run: `npm run generate`

import { writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { parse } from "@babel/parser";
import { FIXTURES } from "../src/fixtures";

const OUT_DIR = resolve(process.cwd(), "src/components/generated");

const HEADER = `// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.
// Run \`npm run generate\` to refresh.

`;

type Imports = {
  shadcn: Set<"Button" | "Input">;
  needsDispatch: boolean;
};

const toPascalCase = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

function renderNode(node: any, imports: Imports, depth = 2): string {
  if (node.type === "JSXText") {
    return node.value.replace(/\s+/g, " ").trim();
  }
  if (node.type !== "JSXElement") return "";

  const name = node.openingElement.name.name as string;
  const props: Record<string, unknown> = {};

  for (const attr of node.openingElement.attributes) {
    if (attr.type !== "JSXAttribute") continue;
    const key = attr.name.name as string;
    const v = attr.value;
    if (v === null) props[key] = true;
    else if (v.type === "StringLiteral") props[key] = v.value;
    else if (v.type === "JSXExpressionContainer") {
      const e = v.expression;
      if (e.type === "NumericLiteral" || e.type === "StringLiteral" || e.type === "BooleanLiteral") {
        props[key] = e.value;
      }
    }
  }

  const children = node.children
    .map((c: any) => renderNode(c, imports, depth + 1))
    .filter((s: string) => s.length > 0);

  return renderShadcn(name, props, children, imports, depth);
}

function renderShadcn(
  name: string,
  props: Record<string, unknown>,
  children: string[],
  imports: Imports,
  depth: number,
): string {
  const pad = "  ".repeat(depth);
  const padOuter = "  ".repeat(depth - 1);
  const inline = (tag: string) => `<${tag}>${children.join("")}</${tag.split(" ")[0]}>`;
  const block = (open: string, close: string) =>
    children.length
      ? `${open}\n${children.map((c) => pad + c).join("\n")}\n${padOuter}${close}`
      : `${open}${close}`;

  switch (name) {
    case "Stack": {
      const gap = props.gap ?? 2;
      return block(`<div className="flex flex-col gap-${gap}">`, `</div>`);
    }
    case "Row": {
      const gap = props.gap ?? 2;
      return block(`<div className="flex flex-row gap-${gap}">`, `</div>`);
    }
    case "Box": {
      const p = props.padding ?? 0;
      return block(`<div className="p-${p}">`, `</div>`);
    }
    case "Text":
      return inline("span");
    case "Heading": {
      const level = (props.level as 1 | 2 | 3 | 4) ?? 2;
      const sizes: Record<number, string> = {
        1: "text-3xl",
        2: "text-2xl",
        3: "text-xl",
        4: "text-lg",
      };
      return block(
        `<h${level} className="${sizes[level]} font-semibold">`,
        `</h${level}>`,
      );
    }
    case "Button": {
      imports.shadcn.add("Button");
      imports.needsDispatch = true;
      const action = JSON.stringify(props.onClick ?? "");
      return block(
        `<Button onClick={() => dispatchAction(${action})}>`,
        `</Button>`,
      );
    }
    case "Input": {
      imports.shadcn.add("Input");
      const attrs: string[] = [];
      if (props.name) attrs.push(`name=${JSON.stringify(props.name)}`);
      if (props.placeholder) attrs.push(`placeholder=${JSON.stringify(props.placeholder)}`);
      if (props.type) attrs.push(`type=${JSON.stringify(props.type)}`);
      return `<Input ${attrs.join(" ")} />`;
    }
    case "Image":
      return `<img src=${JSON.stringify(props.src ?? "")} alt=${JSON.stringify(props.alt ?? "")} />`;
    case "Divider":
      return `<hr className="my-2 border-t" />`;
    default:
      throw new Error(`Unknown semantic component: <${name}>`);
  }
}

function buildImports(imports: Imports): string {
  const lines: string[] = [];
  if (imports.shadcn.has("Button")) lines.push(`import { Button } from "@/components/ui/button";`);
  if (imports.shadcn.has("Input")) lines.push(`import { Input } from "@/components/ui/input";`);
  if (imports.needsDispatch) lines.push(`import { dispatchAction } from "@/ui-jsx/actions";`);
  return lines.join("\n");
}

function generateComponent(componentName: string, jsx: string): string {
  const ast = parse(`<>${jsx.trim()}</>`, { plugins: ["jsx"], sourceType: "module" });
  const expr = (ast.program.body[0] as any).expression;
  const root = expr.children.find((c: any) => c.type === "JSXElement");
  if (!root) throw new Error(`No root element in fixture "${componentName}"`);

  const imports: Imports = { shadcn: new Set(), needsDispatch: false };
  const body = renderNode(root, imports, 2);
  const importBlock = buildImports(imports);

  return (
    HEADER +
    (importBlock ? importBlock + "\n\n" : "") +
    `export function ${componentName}() {\n  return (\n    ${body}\n  );\n}\n`
  );
}

// --- main ---
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const entries = Object.entries(FIXTURES);
for (const [key, jsx] of entries) {
  const componentName = toPascalCase(key);
  const source = generateComponent(componentName, jsx);
  const filePath = join(OUT_DIR, `${componentName}.tsx`);
  writeFileSync(filePath, source);
  console.log(`✓ ${filePath}`);
}

const indexSource =
  HEADER +
  entries
    .map(([k]) => {
      const pc = toPascalCase(k);
      return `export { ${pc} } from "./${pc}";`;
    })
    .join("\n") +
  "\n";
writeFileSync(join(OUT_DIR, "index.ts"), indexSource);
console.log(`✓ ${join(OUT_DIR, "index.ts")}`);
console.log(`\nGenerated ${entries.length} components → src/components/generated/`);
